version: 2
jobs:
  start:
    docker:
      - image: circleci/node:10.16.3
    steps:
      - checkout
      - run:
          name: Run test command
          command: echo 'Run something please!!!!'
      - run:
          name: 'Current branch name'
          command: echo "Branch: $CIRCLE_BRANCH"
  end:
    docker:
      - image: circleci/node:10.16.3
    steps:
      - checkout
      - run:
          name: Something different...
          command: echo 'Something different -___-'
workflows:
  version: 2
  complete_deploy:
    jobs:
      - start
      - end:
          requires:
            - start
